export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_END = 'SUBMIT_FORM_END';
export const UPDATE_AUTH_VALUE = 'UPDATE_AUTH_VALUE';
export const LOGIN = 'LOGIN';
export const REDIRECT = 'REDIRECT';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const MY_PROFILE = 'MY_PROFILE';
export const USERS = 'USERS';
export const SIDER_COLLAPSE = 'SIDER_COLLAPSE';

export const TIMEZONES = 'TIMEZONES';
export const UPDATE_USER = 'UPDATE_USER';
export const CREAT_USER = 'CREAT_USER';
export const METHOD = 'METHOD';
export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const APP_LOAD = 'APP_LOAD';

export const USER_DETAILS = 'USER_DETAILS';
export const USER_DETAILS_CLEAR_ERROR = 'USER_DETAILS_CLEAR_ERROR';
export const DELETE_USER = 'DELETE_USER';

export const USER_LIST_LOADED = 'USER_LIST_LOADED';
export const USER_LIST_UNLOADED = 'USER_LIST_UNLOADED';

export const PREPARE_USER = 'PREPARE_USER';
export const USER_EDITOR_UNLOADED = 'USER_EDITOR_UNLOADED';
export const USER_EDITOR_ADD_NEW = 'USER_EDITOR_ADD_NEW';

export const USER_GROUP_LIST_LOAD = 'USER_GROUP_LIST_LOAD';
export const USER_GROUP_DETAILS_LOAD = 'USER_GROUP_DETAILS_LOAD';
export const USER_GROUP_DETAILS_UNLOAD = 'USER_GROUP_DETAILS_UNLOAD';
export const ALL_MENUS = 'ALL_MENUS';
export const ALLOWED_MENUS = 'ALLOWED_MENUS';

export const USER_GROUP_EDITOR_LOAD = 'USER_GROUP_EDITOR_LOAD';
export const USER_GROUP_EDITOR_UNLOAD = 'USER_GROUP_EDITOR_UNLOAD';
export const CREATE_USER_GROUP = 'CREATE_USER_GROUP';
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP';